name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 6'

jobs:
  test-files:
    name: Test ${{ matrix.swoole-version }} with files against php ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: [ '8.0', '8.1' ]
        swoole-version:
          - swoole-4.4.26
          - swoole-4.5.11
          - swoole-4.6.7
          - swoole-4.7.1
          - swoole-4.8.12
          - swoole-5.0.1
          - swoole
          - openswoole-4.7.2
          - openswoole-4.8.1
          - openswoole-4.9.1
          - openswoole-4.10.0
          - openswoole-4.11.1
          - openswoole-4.12.1
          - openswoole-22.0.0
        include:
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: swoole-4.8.12
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: swoole-5.0.1
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: swoole
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: openswoole-4.12.1
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: openswoole-22.0.0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl, composer, phpunit
          extensions: ${{ matrix.swoole-version }}
          ini-values: session.save_handler=files, session.save_path=/var/lib/php/sessions
          coverage: none
        env:
          fail-fast: true
      - name: Verify PHP environment
        run: php --ri swoole || php --ri openswoole
      - name: Install dependencies
        run: composer install -n
      - name: Update permissions
        run: sudo chown -R $USER:$USER /var/lib/php/sessions
      - name: Run test suite
        run: vendor/bin/phpunit

  test-redis:
    name: Test ${{ matrix.swoole-version }} with redis against php ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: [ '8.0', '8.1' ]
        swoole-version:
          - swoole-4.4.26
          - swoole-4.5.11
          - swoole-4.6.7
          - swoole-4.7.1
          - swoole-4.8.12
          - swoole-5.0.1
          - swoole
          - openswoole-4.7.2
          - openswoole-4.8.1
          - openswoole-4.9.1
          - openswoole-4.10.0
          - openswoole-4.11.1
          - openswoole-4.12.0
        include:
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: swoole-4.8.12
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: swoole-5.0.1
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: swoole
          - os: ubuntu-latest
            php-version: '8.2'
            swoole-version: openswoole-4.12.0
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl, composer, phpunit
          extensions: ${{ matrix.swoole-version }}
          ini-values: session.save_handler=redis, session.save_path=tcp://localhost:6379
          coverage: none
        env:
          fail-fast: true
      - name: Verify PHP environment
        run: php --ri swoole || php --ri openswoole
      - name: Install dependencies
        run: composer install -n
      - name: Run test suite
        run: vendor/bin/phpunit
