name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 6'

jobs:
  test-files:
    name: Test ${{ matrix.swoole-version }} with files against php ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: [ '8.1', '8.2' ]
        swoole-version:
          - swoole-4.8.12
          - swoole-5.0.3
          - swoole-5.1.1
          - swoole
          - openswoole-4.12.1
          - openswoole-22.0.0
          - openswoole-22.1.0
          - openswoole
        include:
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: swoole-5.1.1
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: swoole
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: openswoole-22.1.0
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: openswoole
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl, composer, phpunit
          extensions: ${{ matrix.swoole-version }}
          ini-values: session.save_handler=files, session.save_path=/var/lib/php/sessions
          coverage: none
        env:
          fail-fast: true
      - name: Verify PHP environment
        run: |
          php --ri swoole || php --ri openswoole
          swoole_version="$(php -r "echo defined('SWOOLE_VERSION') ? SWOOLE_VERSION : OPENSWOOLE_VERSION;")"
          [[ "openswoole-$swoole_version" == *"${{ matrix.swoole-version }}"* ]] || exit 1
      - name: Install dependencies
        run: composer install -n
      - name: Update permissions
        run: sudo chown -R $USER:$USER /var/lib/php/sessions
      - name: Run test suite
        run: vendor/bin/phpunit

  test-redis:
    name: Test ${{ matrix.swoole-version }} with redis against php ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test-files
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: [ '8.1', '8.2' ]
        swoole-version:
          - swoole-4.8.12
          - swoole-5.0.3
          - swoole-5.1.1
          - swoole
          - openswoole-4.12.1
          - openswoole-22.0.0
          - openswoole-22.1.0
          - openswoole
        include:
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: swoole-5.1.1
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: swoole
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: openswoole-22.1.0
          - os: ubuntu-latest
            php-version: '8.3'
            swoole-version: openswoole
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl, composer, phpunit
          extensions: ${{ matrix.swoole-version }}
          ini-values: session.save_handler=redis, session.save_path=tcp://localhost:6379
          coverage: none
        env:
          fail-fast: true
      - name: Verify PHP environment
        run: |
          php --ri swoole || php --ri openswoole
          swoole_version="$(php -r "echo defined('SWOOLE_VERSION') ? SWOOLE_VERSION : OPENSWOOLE_VERSION;")"
          [[ "openswoole-$swoole_version" == *"${{ matrix.swoole-version }}"* ]] || exit 1
      - name: Install dependencies
        run: composer install -n
      - name: Run test suite
        run: vendor/bin/phpunit
